@Library('sharedlibrary')_
pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload-Master')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliqittrainings/maven.git")
                }
            }
        }
         stage('ContinuousBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }
        }
        stage('ContinuousDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("http://172.31.20.40:8080","testapp")
                }
            }
        }
        stage('ContinuousTesting_Mater')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliqittrainings/FunctionalTesting.git")
                    cicd.runSelenium("Pipelinewithlibraries")
                }
            }
        }
        stage('ContinuousDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("http://172.31.25.20:8080","prodapp")
                }
            }
        }
        
        
    }
}
